////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

[[s2-create-acl-domains]]
=== s2-create-acl-domains

.Purpose

Creates the domain classes that manage ACL data.

.Example

....
grails s2-create-acl-domains
....

.Description

The plugin includes the required ACL domain classes, but if you want to customize them (for example to configure 2^nd^-level caching) you can use this script to generate the same domain classes in your application's `grails-app/domain` folder to allow minor customization.
