////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

=== Release History

Please read release notes at https://github.com/apache/grails-spring-security/releases for checking release information in the future.

* Version 3.0.0
** Upgraded to Spring Security Core 6.1.0
** Upgraded to Grails Gradle Plugin 6.1.0
** Upgrade Script `init-oauth2` to `ApplicationCommand` to support Grails 6.
* Version 2.0.1
** Update plugin com.gradle.common-custom-user-data-gradle-plugin to v1.12
* Version 2.0.0
** Upgraded to Grails 5.3 with Groovy 3..0.11
** Fixed conflict with logback-config library.
* Version 2.0.0-RC1
** Upgraded to Grails 5.1
* Version 1.0.0
** released