////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

[[introduction]]
== Introduction to the Spring Security OAuth2 Plugin

The OAuth2 Plugin adds oAuth v2 sign-on support to Grails applications that use Spring Security. It depends on the https://github.com/apache/grails-spring-security[Spring Security Core plugin].

It comes with a number of preconfigured OAuth2 providers, but you can implement any provider you like, that is extending the https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/builder/api/DefaultApi20.java[Scribejava DefaultApi20]

include::history.adoc[]