////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

[[Installing]]
== Installing

Add an entry in the dependencies block of your `build.gradle file, changing the version as needed:

[source,groovy]
[subs="attributes"]
.build.gradle
----
dependencies {
   ...
   implementation 'org.grails.plugins:spring-security-acl:{projectVersion}'
   ...
----

Different Branches are built for different versions of Grails

* 5.0.x: Grails 7
* 4.0: Grails 4 through Grails 6
* 3.3.x: Grails 3.3
* grails_32: Grails 3.2
* 2.x: Grails 2


Current version (5.0.x) is for Grails 7 only.

For Grails 3.3.x use:

[source, groovy]
.build.gradle
----
dependencies {
   ...
   implementation 'org.grails.plugins:spring-security-acl:3.2.1'
   ...
----

For previous Grails 3 versions ( 3.0.x, 3.1.x and 3.2.x ) use:

[source, groovy]
.build.gradle
----
dependencies {
   ...
   implementation 'org.grails.plugins:spring-security-acl:3.1.1'
   ...
----

include::installing/distribution.adoc[]

include::installing/snapshots.adoc[]


