////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

== Release History
Please check release notes at https://github.com/apache/grails-spring-security/releases for release history of future releases.

* Version 3.1.0
** released Oct 3, 2017
* Version 2.0.1
** released Oct 3, 2017
* Version 3.0.1
** released May 2, 2017
* Version 3.0.0
** released December 8, 2015
* Version 2.0.0
** released December 7, 2015
* Version 3.0.0.M1
** released September 23, 2015
* Version 2.0-RC1
** released November 11, 2013
* Version 1.0.4
** released July 11, 2012
* Version 1.0.3
** released July 4, 2012
* Version 1.0.2
** released February 12, 2011
* Version 1.0.1
** released September 1, 2010
* Version 1.0
** released July 27, 2010
* Version 0.1
** released June 18, 2010
