////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

[[s2-create-persistent-token]]
=== s2-create-persistent-token

.Purpose

Creates a persistent token domain class for storing remember-me cookie information in the database. The general format is:

[source,bash]
----
./gradlew runCommand "-Pargs=s2-create-persistent-token <classname>"
----

.Example

[source,bash]
----
./gradlew runCommand "-Pargs=s2-create-persistent-token com.yourapp.PersistentLogin"
----

.Description

This creates the domain class in the specified package, and also registers the name in `grails-app/conf/application.groovy`, along with enabling persistent remember-me.
